### ISSUE TITLE
bug with code block

### ISSUE THREAD

**Issue by hstdt** [qeude/SwiftDown#10]
https://user-images.githubusercontent.com/10215098/167287572-ca8aaa28-d025-48a0-b263-0dcc2fdb3304.mov

PS:
Theme is customized.

**Comment by hstdt** [comment]
The problem disappears when roll back to 6fdef58300d0a4fe39ffe0cad5a04384b81e5f9a.

**Comment by qeude** [comment]
Hi!
There is a pending PR #17 if you want to give a try before I merge it and create a new release :D
