### ISSUE TITLE
Cursor jumping to the end of line

### ISSUE THREAD

**Issue by edimoldovan** [qeude/SwiftDown#11]
Hi! I am experiencing a cursor jump to the end of text on each formatting being applied. Anything I could do to stop this from happening?

**Comment by qeude** [comment]
Hi! Could you please tell me on which platform you are trying to use SwiftDown and on which this occurs please? 🙌🏼

**Comment by edimoldovan** [comment]
Yes, sure. I tried it in an iOS app. Latest stable release I believe.

**Comment by hstdt** [comment]
@edimoldovan  same as #10 ?

**Comment by edimoldovan** [comment]
I didn't watch the video carefully enough, it seams. Same issue as #10.

**Comment by yonaskolb** [comment]
I'm getting this too on macOS 12.4 with Xcode 14. The issue occurs when navigating within the markdown with arrow keys and then typing. Instead of the focus staying where you typed, it jumps to the end of the string

**Comment by paulja** [comment]
+1

**Comment by niravbhimani53** [comment]
Issue observed with Bold Italic.

https://user-images.githubusercontent.com/12537912/182014932-6368bbdf-ee06-4ca9-bbb1-3eaf6f9b4ca6.mov

**Comment by scotch115** [comment]
Also getting this issue, +1

**Comment by leonschrijvers** [comment]
This issue can also be reproduced on macOS Ventura 13.0.1 with Xcode 14.1. It makes this package unusable as an editor, which is too bad because it has so much potential. I would love to help to figure this out, but my experience with Swift and SwiftUI is still limited, so it's hard to figure out where to start.

**Comment by qeude** [comment]
Hi!
There is a PR #17, if anyone want to give a try before I merge it and I release an update of the package?
