### ISSUE TITLE
Automatically focus `SwiftDownEditor`?

### ISSUE THREAD

**Issue by dnlfrst** [qeude/SwiftDown#12]
Is there any way to force `SwiftDownEditor` to automatically receive the focus on iOS?

**Comment by qeude** [comment]
Hi @dnlfrst, sorry for the very late answer, I've been busy and wasn't able to work on side projects.
I think you could make use of the [`FocusState`](https://developer.apple.com/documentation/swiftui/focusstate) like so [here](https://github.com/qeude/SwiftDown/commit/b5df198c872d4679a47e0da83053c7f1289f1042)
