### ISSUE TITLE
Styling is not applied when using navigation

### ISSUE THREAD

**Issue by leonschrijvers** [qeude/SwiftDown#15]
First of all: SwiftDown is a great package! I tried several markdown editor packages that support live styling and SwiftDown has by far the best editing experience.

There is one thing I am struggling with: it appears that styling is only applied when editing text (so typing in the editor), but not when the view is initially loaded. This can be demonstrated when you use navigation in a project, e.g. have a list of documents and when you click on a document, the corresponding contents are being shown in a SwiftDown view. Initially all text has the same color and font size, but if you give SwiftDown focus and type one character, then all styling gets updated.

I tried to fiddle with the `.onAppear()` modifier, but is unclear to me how I could trigger 'update styling' in the SwiftDownEditor. Does someone has an idea how to handle this? Thanks in advance!

**Comment by qeude** [comment]
Hey @leonschrijvers, thanks for your feedback, I didn't take a look at SwiftDown for a long time since it's a side project and since I've been busy but I'll definitely try to solve pending issue in early 2023 🙌

**Comment by qeude** [comment]
@leonschrijvers I just opened a PR that should fix the problem exposed here, if you want to take a look before I merge it 🙌🏼

**Comment by leonschrijvers** [comment]
@qeude  I tried the fix of the PR and the styling is now directly applied (exactly as shown in the gif from the PR). Tested with a macOS app at Ventura 13.0.1. Thanks for fixing this issue so quickly!

**Comment by qeude** [comment]
@leonschrijvers thanks for trying, I'll try to make a release with this fix and the cursor jumping fix as soon as possible 🙌
