### ISSUE TITLE
4 errors when loading

### ISSUE THREAD

**Issue by hutsonphd** [qeude/SwiftDown#2]
1. "Value of type 'ShiftDown' has not member 'onTextChange'" - SwiftDownEditor.swift
2. "Missing argument for parameter 'offset' in call" - SwiftDownEditor.swift
3. "Cannot find 'textView' in scope" - SwiftDownEditor.swift
4. "Cannot find 'textView" in scope" - SwiftDownEditor.swift

<img width="1476" alt="Screen Shot 2021-03-22 at 8 24 03 PM" src="https://user-images.githubusercontent.com/7184184/112078504-8cbe7700-8b4c-11eb-8cc8-f5f0890538a5.png">

**Comment by qeude** [comment]
Thanks for your feedback, I will resolve this as soon as possible 😄 You are experiencing this on the `performance-improvements` branch aren't you ?
