### ISSUE TITLE
Cannot resolve package dependencies?

### ISSUE THREAD

**Issue by RosTeHeA** [qeude/SwiftDown#21]
Any idea why I'm getting this error when I try to add it via Package Manager?
Failed to resolve dependencies Dependencies could not be resolved because root depends on 'swiftdown' 0.3.0..<1.0.0

**Comment by RosTeHeA** [comment]
False alarm - I was trying to install the "develop" branch instead of "main"

**Comment by ingun37** [comment]
I'm having the same problem and I don't understand the answer. Do you mean you fixed by setting dependency rule  to *main branch* instead of *Up to next major version*?

**Comment by sergeymild** [comment]
i have the same error

**Comment by sergeymild** [comment]
I have the same error, event if i set `main` branch i receive

```
Failed to resolve dependencies Dependencies could not be resolved because package 'swiftdown' is required using a stable-version but 'swiftdown' depends on an unstable-version package 'swiftlint' and root depends on 'swiftdown' 0.3.0.

```

**Comment by qeude** [comment]
Hi!

Thanks all for your feedback, I just released a [newer version](https://github.com/qeude/SwiftDown/releases/tag/0.3.1) that just fix that. 
Hope it'll help you folks 🙏🏼
