### ISSUE TITLE
Cannot resolve package dependencies?

### ISSUE THREAD

**Issue by sergeymild** [qeude/SwiftDown#22]
After add dependency i always receive this error

Failed to resolve dependencies Dependencies could not be resolved because package 'swiftdown' is required using a stable-version but 'swiftdown' depends on an unstable-version package 'swiftlint' and root depends on 'swiftdown' 0.3.0.

**Comment by qeude** [comment]
Hi! 

Thanks for the feedback, I just released a [new version](https://github.com/qeude/SwiftDown/releases/tag/0.3.1) that hopefully solves that. Hope it will help you!

**Comment by sergeymild** [comment]
now it works) thanks
