### ISSUE TITLE
Plug-in ended with uncaught signal: 5)

### ISSUE THREAD

**Issue by asnewman** [qeude/SwiftDown#24]
**Describe the bug**
Adding the package to my iOS 16 project causes the error `Plug-in ended with uncaught signal: 5)`

**To Reproduce**
1. Add Swiftdown as a dependency via the Xcode dependency manager
2. See error

**Additional context**
I'm using Version 14.3.1 on a project for iOS 16

**Comment by runkaiz** [comment]
It is an issue with SwiftLint, you can install it through brew (I am actually not sure if you need to do that), as for the plug-in issue refer to this https://github.com/realm/SwiftLint/issues/1466#issuecomment-297265863
It helped me with my local environment, but unfortunately I have encountered this exactly issue when deploying to Xcode Cloud.

**Comment by qeude** [comment]
Thanks for reporting this, I finally remove the plugin to use brew instead
