### ISSUE TITLE
README - minor correction

### ISSUE THREAD

**Issue by VerticalHeretic** [qeude/SwiftDown#3]
There is a minor error in README, when you try using @Binding it will throw error: 
![Screenshot 2021-04-08 at 19 32 24](https://user-images.githubusercontent.com/31141451/114071820-db387900-98a1-11eb-9156-20e9cad7a7ac.png)
You should use @State there and it will work as intended.

**Comment by qeude** [comment]
You are right, it would be clearer to have a sample code that works out of the box. I'm going to change this.
