### ISSUE TITLE
Enter a space first and then the # symbol, an error will occur

### ISSUE THREAD

**Issue by iamiota** [qeude/SwiftDown#32]
**Describe the bug**

**To Reproduce**
1. Input a " "(Space)
2. Input a "#"
3. See error

**Expected behavior**

**Screenshots**

`toMarkdownNode` method in `MarkdownEngine.swift`
error: `Swift/StringUTF8View.swift:192: Fatal error: String index is out of bounds`

**Desktop (please complete the following information):**
 - OS: Sonoma
 - Version 14.2.1

**Additional context**

**Comment by qeude** [comment]
👋 Hey, thanks for opening an issue about this, could you check if this [PR](https://github.com/qeude/SwiftDown/pull/33) works for you? 🙏

**Comment by iamiota** [comment]
@qeude It worked, thank you very much.
